=== HendrysTobar/Demos-IngSw3/02 - EjemploXML_XSD/Simon/StillSets/StillSet.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:element name="StillSet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Stills" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Still" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Texto" type="xs:string" minOccurs="1" />
                    <xs:element name="PosTexto" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="x" type="xs:int" minOccurs="1" />
                          <xs:element name="y" type="xs:int" minOccurs="1" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Nombre" type="xs:string" />
                  <xs:attribute name="Imagen" type="xs:string" />
                  <xs:attribute name="ArchivoSonido" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Nombre" type="xs:string" />
      <xs:attribute name="AudioFondo" type="xs:string" />
    </xs:complexType>
  </xs:element>  
</xs:schema>

=== HendrysTobar/Demos-IngSw3/02 - EjemploXML_XSD/Simon/StillSets/StillSetInicio.xml
<?xml version="1.0" encoding="utf-8"?>
<StillSet Nombre="StillSetInicio" AudioFondo ="Sonidos/OOTFS.mp3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./StillSet.xsd">
    <Stills>       
        <Still Nombre="Still3" Imagen ="IntroStill1.jpg" ArchivoSonido ="Sonidos/Narraciones/Narracion 1.wav">
            <Texto>
Hace mas de 25 anos, cuando todas las personas se preparaban para el
feliz dia de inauguracion del carnaval de aquel ano. Llegaron noticias
lejanas por boca de un mensajero a oidos del alcalde, diciendo que en
los pueblos del norte habian sucedido cosas extranas. Muchos de sus
habitantes estaban sufriendo una clase de enfermedad desconocida que
despues de un tiempo habia cobrado la vida de varias personas… </Texto>
            <PosTexto>
                <x>
                    30
                </x>
                <y>
                    50
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still4" Imagen ="IntroStill1.jpg" ArchivoSonido ="Sonidos/Narraciones/Narracion 2.mp3">
            <Texto>
Con la extrana enfermedad habia llegado tambien un brujo curandero
llamado Kash; que decia que tenia el poder de curarlos a todos y que
nadie mas tendria que sufrir. Los alcaldes de los pueblos atonitos por
aquella enfermedad que cada dia se veia mas como una peste decidieron
dar todos los recursos a su alcance para que aquel brillante brujo los
salvara. Sin embargo, a medida que el brujo actuaba y daba instrucciones
a los habitantes para que hicieran y dejaran de hacer ciertas cosas como
habitos de salud y de limpieza, las personas de aquellos lugares enfermaban
cada dia mas y mas… </Texto>
            <PosTexto>
                <x>
                    30
                </x>
                <y>
                    50
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still6" Imagen ="IntroStill1.jpg" ArchivoSonido ="Sonidos/Narraciones/Narracion 3.mp3">
            <Texto>
Kash tomo el poder de cientos de pueblos, y asi poco a poco durante un
largo tiempo fue tornandose cada dia mas poderoso hasta que no hubo mas
que ocultar. En vez de evitar que la gente enfermara, estaba causando
que aquella peste se extendiera mas y mas. En su malevola busqueda de
crear un imparable imperio, creo de si mismo cientos de subditos
similares a el, formando un enorme ejercito encargado de fomentar
el crecimiento de aquella terrible enfermedad, su nombre fue
desvelado: La tuberculosis.</Texto>
            <PosTexto>
                <x>
                    10
                </x>
                <y>
                    10
                </y>
            </PosTexto>
        </Still>       
        <Still Nombre="Still10" Imagen ="IntroStill1.jpg" ArchivoSonido ="Sonidos/Narraciones/Narracion 4.mp3">
            <Texto>
Sin embargo esta historia en realidad no trata de como las personas
se resignaron a vivir bajo el malevolo imperio de Kash. Por el contrario,
se trata de la esperanza que aun existe en los corazones de muchos,
particularmente en una pequena familia que a escondidas del emperador
y de manera ilegal a sus mandatos, mantiene bajo su casa una pequena
enfermeria donde una bella mujer viuda de la guerra, con ayuda de su
padre veterano de guerra y su pequeno e inteligente hijo Simon de
trece anos, asisten a los enfermos mas graves, con la finalidad de
hacerles mas llevaderos sus dias a pesar de desconocer las causas y el
tratamiento para la enfermedad. </Texto>
            <PosTexto>
                <x>
                    10
                </x>
                <y>
                    10
                </y>
            </PosTexto>
        </Still>
    </Stills>    
</StillSet>

=== HendrysTobar/Demos-IngSw3/02 - EjemploXML_XSD/Simon/StillSets/StillSetLlegaOrah.xml
<?xml version="1.0" encoding="utf-8"?>
<StillSet Nombre="StillSetLLegaOrah" AudioFondo ="Sonidos/OOTFS.mp3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./StillSet.xsd">
    <Stills>
        <Still Nombre="Still1" Imagen ="IntroStill1.jpg" ArchivoSonido ="">
            <Texto>
SIMON:
Listo mama, aqui estoy con Don Nicolas como me lo pediste.

ESPERANZA:
muy bien Simon, entra rapido antes de que algun guardia nos vea!
            </Texto>
            <PosTexto>
                <x>
                   10
                </x>
                <y>
                    10
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still2" Imagen ="IntroStill2.jpg" ArchivoSonido ="">
            <Texto>DON NICOLAS: muchas gracias Dona Esperanza... coff, coff… no se
imagina lo agradecido que estoy con usted.

Sabe una cosa, de la cual me di cuenta!!! Note que la enfermedad se
propagaba mas aun en grupos de personas INDIGENTES y DROGADICTAS!!!
No se por que ni cual será la razón!!

ABUELO: Siga Don Nicolas, por aqui por estas gradas hacia abajo.

            </Texto>
            <PosTexto>
                
                <x>
                    10
                </x>
                <y>
                    10
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still3" Imagen ="IntroStill1.jpg" ArchivoSonido ="">
            <Texto>
SIMON: Mama, tengo un raro presentimiento… Cuando pasabamos
por el camino habia un soldado que me dejo pasar, sin embargo
cuando volviamos ya no estaba… tu sabes que ellos no suelen 
dejar sus guardias.

ESPERANZA: Que extrano… espero que no suceda nada ma….

            </Texto>
            <PosTexto>
                <x>
                    30
                </x>
                <y>
                    50
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still4" Imagen ="IntroStill1.jpg" ArchivoSonido ="">
            <Texto>
SOLDADO: Por fin los hemos descubierto... ATRAPENLOS!
            </Texto>
            <PosTexto>
                <x>
                    30
                </x>
                <y>
                    50
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still5" Imagen ="IntroStill1.jpg" ArchivoSonido ="">
            <Texto>
ESPERANZA: Simon Huye!!! Salvate hijo mio no te
preocupes por nosotros!

SIMON: abuelo!... Mama!... NOOOooo...

            </Texto>
            <PosTexto>
                <x>
                    10
                </x>
                <y>
                    10
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still6" Imagen ="IntroStill1.jpg" ArchivoSonido ="">
            <Texto>
SIMON: Sniff, sniff… todo esto es mi culpa, ese guardia
me estaba siguiendo… con razon los demas nunca me
detuvieron. Todo era una trampa!
            </Texto>
            <PosTexto>
                <x>
                    10
                </x>
                <y>
                    10
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still7" Imagen ="IntroStill1.jpg" ArchivoSonido ="">
            <Texto>
SIMON: Papa… desde el cielo te ruego que me ayudes!...
            </Texto>
            <PosTexto>
                
                <x>
                    10
                </x>
                <y>
                    10
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still8" Imagen ="IntroStill1.jpg" ArchivoSonido ="">
            <Texto>
SIMON: sniff, sniff… No se que hacer, ahora estamos
todos perdidos… sniff, sniff… por todos los cielos
papa tu que estas viendome.. ayudame!!
            </Texto>
            <PosTexto>
                <x>
                    10
                </x>
                <y>
                    10
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still9" Imagen ="IntroStill1.jpg" ArchivoSonido ="">
            <Texto>
ORAH: Todo no esta perdido pequeno Simon… Tus ruegos
han sido escuchados en todos los rincones del Cielo
y te han dado la oportunidad de salvar a tu pueblo…
Debes ser muy valiente y estar atento a cualquier
pista o mensaje que las estrellas pongan en tu camino.
            </Texto>
            <PosTexto>
                <x>
                    10
                </x>
                <y>
                    10
                </y>
            </PosTexto>
        </Still>
        <Still Nombre="Still10" Imagen ="IntroStill1.jpg" ArchivoSonido ="">
            <Texto>
SIMON: Tu quien eres!?!

ORAH: Mi nombre es Orah, soy la eterna encargada del
tiempo, y ahora voy a ser quien te va a ayudar en
tu busqueda por la salvacion de tu gente… Es hora de
que nos vamos de este lugar, ven pequeno en el camino
te ire contando que vamos a hacer.
            </Texto>
            <PosTexto>
                <x>
                    10
                </x>
                <y>
                    10
                </y>
            </PosTexto>
        </Still>
    </Stills>    
</StillSet>
