=== HendrysTobar/Demos-IngSw3/02 - EjemploXML_XSD/Simon/guion.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Guion" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Guion">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="GuionPart">
                    <xs:complexType>
                        <xs:attribute name="Tipo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="playStillSet" />
                                    <xs:enumeration value="playMundo" />
                                    <xs:enumeration value="gameOver" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="Argumentos" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== HendrysTobar/Demos-IngSw3/02 - EjemploXML_XSD/Simon/guion.xml
<?xml version="1.0" encoding="utf-8"?>
<Guion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./guion.xsd">
	<GuionPart Tipo ="playStillSet" Argumentos ="StillSetInicio"/>
    <GuionPart Tipo ="playMundo" Argumentos ="Mundos/SanJoseDeLasPiedras1.xml"/>
    <GuionPart Tipo ="playMundo" Argumentos ="Mundos/SanJoseDeLasPiedras2.xml"/>
    <GuionPart Tipo ="playStillSet" Argumentos ="StillSetLLegaOrah"/>
    <GuionPart Tipo ="playMundo" Argumentos ="Mundos/SanJoseDeLasPiedras3.xml"/>
    <GuionPart Tipo ="playMundo" Argumentos ="Mundos/SanJoseDeLasPiedras4.xml"/>
    <GuionPart Tipo="gameOver"/>

</Guion>
