=== HendrysTobar/Demos-IngSw3/02 - EjemploXML_XSD/Simon/Mundos/Mundo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="SchemaMundo" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Posicion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="x" type="xs:float" minOccurs="1" maxOccurs="1" />
                <xs:element name="y" type="xs:float" minOccurs="1" maxOccurs="1" />
                <xs:element name="z" type="xs:float" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Escala">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="x" type="xs:float" minOccurs="1" maxOccurs="1" />
                <xs:element name="y" type="xs:float" minOccurs="1" maxOccurs="1" />
                <xs:element name="z" type="xs:float" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Direccion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="x" type="xs:float" minOccurs="1" maxOccurs="1" />
                <xs:element name="y" type="xs:float" minOccurs="1" maxOccurs="1" />
                <xs:element name="z" type="xs:float" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ConversacionRef">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ConversacionRef" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="Descripcion" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="Condicion" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="CondicionBasica" minOccurs="0" maxOccurs="unbounded" />
                                        <xs:element name="Either" type="Either" minOccurs="0" maxOccurs="1" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="IdConversacion" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="CondicionBasica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CondicionBasica" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="NombreFlag" type="xs:string" />
            <xs:attribute name="Activa" type="xs:boolean" />
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Either">
        <xs:sequence>
            <xs:element name="CondicionBasica">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="CondicionBasica" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="DatosMundo">
        <xs:complexType>
            <xs:all>
                <xs:element name="Skydome" type="xs:string" minOccurs="0" />
                <xs:element name="Nombre" type="xs:string" minOccurs="0" />
                <xs:element name="Fog" type="xs:boolean" minOccurs="0" />
                <xs:element name="Terreno" type="xs:string" minOccurs="0" />
                <xs:element name="WorldSizeX" type="xs:int" minOccurs="0" />
                <xs:element name="WorldSizeZ" type="xs:int" minOccurs="0" />
                <xs:element name="MaxHeight" type="xs:int" minOccurs="0" />
                <xs:element name="MatMuro" type="xs:string" minOccurs="0" />
                <xs:element name="simon" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="NombreObjeto" type="xs:string" minOccurs="1" default="Simon" />
                            <xs:element name="ModeloFile" type="xs:string" minOccurs="1" />
                            <xs:element name="Rapidez" type="xs:float" minOccurs="0" default="1.0" />
                            <xs:element name="Estado" type="xs:string" minOccurs="0" default="Idle" />
                            <xs:element name="Cara" type="xs:string" minOccurs="0" />
                            <xs:element ref="Posicion" minOccurs="1" />
                            <xs:element ref="Escala" minOccurs="1" />
                            <xs:element ref="Direccion" minOccurs="1" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="orah" minOccurs="0">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="NombreObjeto" type="xs:string" minOccurs="1" default="Orah" />
                            <xs:element name="ModeloFile" type="xs:string" minOccurs="1" />
                            <xs:element name="Rapidez" type="xs:float" minOccurs="0" default="1.0" />
                            <xs:element name="Estado" type="xs:string" minOccurs="0" default="Idle" />
                            <xs:element name="Cara" type="xs:string" minOccurs="0" />
                            <xs:element name="CaminarADestino" type="xs:boolean" minOccurs="0" default="false" />
                            <xs:element ref="Posicion" minOccurs="1" />
                            <xs:element ref="Escala" minOccurs="1" />
                            <xs:element ref="Direccion" minOccurs="1" />
                            <xs:element ref="ConversacionRef" minOccurs="0" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="SceneObjects" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DatosSceneObject" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="NombreObjeto" type="xs:string" minOccurs="1" />
                                        <xs:element name="ModeloFile" type="xs:string" minOccurs="1" />
                                        <xs:element ref="Posicion" minOccurs="1" maxOccurs="1" />
                                        <xs:element ref="Escala" minOccurs="1" maxOccurs="1" />
                                        <xs:element ref="Direccion" minOccurs="0" maxOccurs="1">
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Personajes" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DatosPersonaje" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="NombreObjeto" type="xs:string" minOccurs="1" />
                                        <xs:element name="ModeloFile" type="xs:string" minOccurs="1" />
                                        <xs:element name="Rapidez" type="xs:float" minOccurs="1" default="1.0" />
                                        <xs:element name="Estado" type="xs:string" minOccurs="1" default="Idle" />
                                        <xs:element name="Cara" type="xs:string" minOccurs="1" />
                                        <xs:element ref="Posicion" minOccurs="1" />
                                        <xs:element ref="Escala" minOccurs="1" />
                                        <xs:element ref="Direccion" minOccurs="1" />
                                        <xs:element ref="ConversacionRef" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="CaminarADestino" type="xs:boolean" default="false" minOccurs="0" maxOccurs="1" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute name="AudioAmbientacion" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== HendrysTobar/Demos-IngSw3/02 - EjemploXML_XSD/Simon/Mundos/SanJoseDeLasPiedras1.xml
<?xml version="1.0" encoding="utf-8"?>
<DatosMundo xsi:noNamespaceSchemaLocation="./Mundo.xsd" AudioAmbientacion="Sonidos/Prelude.mp3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <simon>
        <NombreObjeto>Simon</NombreObjeto>
        <ModeloFile>simoncuerpo.mesh</ModeloFile>
        <Rapidez>40.0</Rapidez>
        <Estado>Idle</Estado>
        <Cara>simon-icono.png</Cara>
        <Posicion>
            <x>3381.702</x>
            <y>0</y>
            <z>13369.53</z>
        </Posicion>
        <Escala>
            <x>1.0</x>
            <y>1.0</y>
            <z>1.0</z>
        </Escala>
        <Direccion>
            <x>1.0</x>
            <y>0.0</y>
            <z>-1.0</z>
        </Direccion>
    </simon>    
    <SceneObjects>
        <!--Casas-->
        <DatosSceneObject>
            <NombreObjeto>Casa de Simon</NombreObjeto>
            <Posicion>
                <x>3885.858</x>
                <y>17.36212</y>
                <z>12068.42</z>
            </Posicion>
            <Escala>
                <x>4.0</x>
                <y>4.0</y>
                <z>4.0</z>
            </Escala>
            <Direccion>
                <x>0.0</x>
                <y>-1.0</y>
                <z>0.0</z>
            </Direccion>
            <ModeloFile>casasimon.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>Casa Mayor</NombreObjeto>
            <Posicion>
                <x>7752.504</x>
                <y>331.1619</y>
                <z>2034.559</z>
            </Posicion>
            <Escala>
                <x>4.0</x>
                <y>4.0</y>
                <z>4.0</z>
            </Escala>
            <ModeloFile>casamayor.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>casa 3</NombreObjeto>
            <Posicion>
                <x>11996.79</x>
                <y>332.1106</y>
                <z>11251.93</z>
            </Posicion>
            <Escala>
                <x>4.0</x>
                <y>4.0</y>
                <z>4.0</z>
            </Escala>
            <Direccion>
                <x>0.0</x>
                <y>-1.0</y>
                <z>0.0</z>
            </Direccion>
            <ModeloFile>casados.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>casa 1A</NombreObjeto>
            <Posicion>
                <x>4389.324</x>
                <y>151.1935</y>
                <z>8724.644</z>
            </Posicion>
            <Escala>
                <x>4.0</x>
                <y>4.0</y>
                <z>4.0</z>
            </Escala>
            <Direccion>
                <x>0.0</x>
                <y>-1.0</y>
                <z>0.0</z>
            </Direccion>
            <ModeloFile>casaunoA.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>casa 1B</NombreObjeto>
            <Posicion>
                <x>9518.372</x>
                <y>19.29699</y>
                <z>12510.56</z>
            </Posicion>
            <Escala>
                <x>4.0</x>
                <y>4.0</y>
                <z>4.0</z>
            </Escala>
            <Direccion>
                <x>0.0</x>
                <y>-1.0</y>
                <z>0.0</z>
            </Direccion>
            <ModeloFile>casaunoB.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>casa 4</NombreObjeto>
            <Posicion>
                <x>2152.68335</x>
                <y>66.66667</y>
                <z>4540.374</z>
            </Posicion>
            <Escala>
                <x>3.5</x>
                <y>3.5</y>
                <z>3.5</z>
            </Escala>
            <ModeloFile>casados.mesh</ModeloFile>
            <Direccion>
                <x>0</x>
                <y>-1</y>
                <z>0</z>
            </Direccion>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>casa 5</NombreObjeto>
            <Posicion>
                <x>5487.03369</x>
                <y>16.8264656</y>
                <z>4439.2334</z>
            </Posicion>
            <Escala>
                <x>3</x>
                <y>3</y>
                <z>3</z>
            </Escala>
            <ModeloFile>casados.mesh</ModeloFile>
            <Direccion>
                <x>0</x>
                <y>-1</y>
                <z>0</z>
            </Direccion>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>casa 6</NombreObjeto>
            <Posicion>
                <x>5487.924</x>
                <y>15.6862755</y>
                <z>5851.994</z>
            </Posicion>
            <Escala>
                <x>3</x>
                <y>3</y>
                <z>3</z>
            </Escala>
            <ModeloFile>casados.mesh</ModeloFile>
            <Direccion>
                <x>0</x>
                <y>-1</y>
                <z>0</z>
            </Direccion>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>casa 7</NombreObjeto>
            <Posicion>
                <x>12435.5938</x>
                <y>19.6078434</y>
                <z>2910.89331</z>
            </Posicion>
            <Escala>
                <x>3</x>
                <y>3</y>
                <z>3</z>
            </Escala>
            <ModeloFile>casaunoA.mesh</ModeloFile>
            <Direccion>
                <x>0</x>
                <y>-1</y>
                <z>0</z>
            </Direccion>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>casa 8</NombreObjeto>
            <Posicion>
                <x>14320.1143</x>
                <y>19.6078434</y>
                <z>4585.181</z>
            </Posicion>
            <Escala>
                <x>3</x>
                <y>3</y>
                <z>3</z>
            </Escala>
            <ModeloFile>casaunoB.mesh</ModeloFile>
            <Direccion>
                <x>0</x>
                <y>-1</y>
                <z>0</z>
            </Direccion>
        </DatosSceneObject>
        
        
        <!--Arboles-->
        
        
        <DatosSceneObject>
            <NombreObjeto>arbol 1</NombreObjeto>
            <Posicion>
                <x>2210.123</x>
                <y>18.75533</y>
                <z>12327.5</z>
            </Posicion>
            <Escala>
                <x>2.0</x>
                <y>2.0</y>
                <z>2.0</z>
            </Escala>
            <ModeloFile>arbol.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>arbol 2</NombreObjeto>
            <Posicion>
                <x>5898.088</x>
                <y>19.87831</y>
                <z>11883.09</z>
            </Posicion>
            <Escala>
                <x>2.0</x>
                <y>2.0</y>
                <z>2.0</z>
            </Escala>
            <ModeloFile>arbol.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>arbol 3</NombreObjeto>
            <Posicion>
                <x>3234.375</x>
                <y>16.61347</y>
                <z>14087</z>
            </Posicion>
            <Escala>
                <x>2.0</x>
                <y>2.0</y>
                <z>2.0</z>
            </Escala>
            <ModeloFile>arbol.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>arbol 4</NombreObjeto>
            <Posicion>
                <x>3125.704</x>
                <y>106.6089</y>
                <z>7517.362</z>
            </Posicion>
            <Escala>
                <x>2.0</x>
                <y>2.0</y>
                <z>2.0</z>
            </Escala>
            <ModeloFile>arbol.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>arbol 5</NombreObjeto>
            <Posicion>
                <x>4086.124</x>
                <y>96.3204</y>
                <z>7428.565</z>
            </Posicion>
            <Escala>
                <x>2.0</x>
                <y>2.0</y>
                <z>2.0</z>
            </Escala>
            <ModeloFile>arbol.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>arbol 6</NombreObjeto>
            <Posicion>
                <x>622.1459</x>
                <y>70.38438</y>
                <z>7823.789</z>
            </Posicion>
            <Escala>
                <x>2.0</x>
                <y>2.0</y>
                <z>2.0</z>
            </Escala>
            <ModeloFile>arbol.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>arbol 7</NombreObjeto>
            <Posicion>
                <x>8302.282</x>
                <y>16.15438</y>
                <z>14370</z>
            </Posicion>
            <Escala>
                <x>2.0</x>
                <y>2.0</y>
                <z>2.0</z>
            </Escala>
            <ModeloFile>arbol.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>arbol 8</NombreObjeto>
            <Posicion>
                <x>14545.37</x>
                <y>54.90197</y>
                <z>13978.61</z>
            </Posicion>
            <Escala>
                <x>2.0</x>
                <y>2.0</y>
                <z>2.0</z>
            </Escala>
            <ModeloFile>arbol.mesh</ModeloFile>
        </DatosSceneObject>
        <DatosSceneObject>
            <NombreObjeto>arbol 9</NombreObjeto>
            <Posicion>
                <x>6741.94629</x>
                <y>19.2224846</y>
                <z>9612.254</z>
            </Posicion>
            <Escala>
                <x>1</x>
                <y>1</y>
                <z>1</z>
            </Escala>
            <ModeloFile>arbol.mesh</ModeloFile>
